default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jessiesun # Replace with your actual username
  password: Sr6208H%llo1019 # Replace with your actual password, if you have one
  host: localhost

development:
  <<: *default
  database: jack_o_translate_development

test:
  <<: *default
  database: jack_o_translate_test

production:
  <<: *default
  database: jack_o_translate_production
  url: <%= ENV['DATABASE_URL'] %>
